name: flutter_dom_ui
description: "A new universal Flutter Web Seo package."
version: 0.0.2
homepage: https://github.com/nahidhasan-dev/flutterdomui

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
